### ISSUE TITLE
Extending to similarity ratings

### ISSUE THREAD

**Issue by rgerkin** [psiz-org/psiz#10]
@roads This is really cool (I just read the paper).  I'm interested in extending this to similarity ratings instead of rankings (I work in olfaction and between slow trials and short working memory comparing triplets has limitations).  Would there be any major conceptual limitations to extending this to similarity ratings?  Other than writing a lot of code (which I would be contributing)?

**Comment by roads** [comment]
Hi @rgerkin, your work sounds super neat! Extending this package to similarity ratings has been a recent goal of mine, it would be great to collaborate. As you guessed, extending this package will require writing a fair amount of new code and refactoring some old classes.

The major components that would need to be addressed:
* Refactor the trials module to have a more inclusive abstract base class
* Add classes for paired similarity ratings
* Add a subclass of PsychologicalEmbedding (along with a TensorFlow layer) that handles the cognitive/decision logic of paired similarity judgments.

I don't know if you're interested in active learning for paired similarity ratings as well, but I don't see any theoretical hurdles there either.

I'm stretched pretty thin at the moment, but perhaps we could chat about good contracts for the various classes. I could then modify some of the existing code to pave they way for a pull request.

**Comment by roads** [comment]
@rgerkin I should add that I'm currently working on a major refactor that aligns PsiZ more closely with TensorFlow idioms. You can see it on the branch `decoupled-restarts`. Still a work in progress...

**Comment by roads** [comment]
Similarity ratings can be learned using a model that uses a `Logistic` layer. See [examples/rate/mle_1g.py](https://github.com/psiz-org/psiz/blob/main/examples/rate/mle_1g.py) for an example.
